-- Debt2Test persistence schema.
-- Flyway owns this schema; Hibernate runs with ddl-auto=validate and never alters it.
-- CHECK constraints deliberately restate invariants already enforced by the debt-core
-- records, so a future writer that bypasses those records still cannot store nonsense.

CREATE TABLE pipeline_run (
    id                         UUID         PRIMARY KEY,
    run_id                     VARCHAR(255),
    repository_url             TEXT         NOT NULL,
    requested_revision         VARCHAR(255),
    resolved_revision          VARCHAR(255),
    status                     VARCHAR(32)  NOT NULL,
    started_at                 TIMESTAMPTZ  NOT NULL,
    finished_at                TIMESTAMPTZ,
    triggered_by               VARCHAR(255),
    context_enabled            BOOLEAN      NOT NULL,
    heuristic_fallback_allowed BOOLEAN      NOT NULL,
    test_framework             VARCHAR(64),
    prompt_version             VARCHAR(64),
    candidate_count            INTEGER      NOT NULL DEFAULT 0,
    satd_count                 INTEGER      NOT NULL DEFAULT 0,
    generated_test_count       INTEGER      NOT NULL DEFAULT 0,
    report_paths               TEXT,
    CONSTRAINT uq_pipeline_run_run_id UNIQUE (run_id),
    CONSTRAINT ck_pipeline_run_status CHECK (status IN
        ('QUEUED','RUNNING','COMPLETED','COMPLETED_WITH_ERRORS','FAILED','CANCELLED'))
);

CREATE TABLE technical_debt (
    id                        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                    UUID         NOT NULL
                                  REFERENCES pipeline_run(id) ON DELETE CASCADE,
    candidate_id              VARCHAR(255) NOT NULL,
    file_path                 TEXT         NOT NULL,
    method_name               TEXT         NOT NULL,
    line_number               INTEGER      NOT NULL,
    comment                   TEXT         NOT NULL,
    method_source_code        TEXT         NOT NULL,
    source_repository_url     TEXT         NOT NULL,
    source_revision           VARCHAR(255),
    source_relative_file_path TEXT         NOT NULL,
    satd                      BOOLEAN,
    debt_type                 VARCHAR(128),
    confidence                DOUBLE PRECISION,
    classifier_provider       VARCHAR(64),
    classifier_strategy       VARCHAR(64),
    classifier_version        VARCHAR(64),
    item_status               VARCHAR(32),
    extracted_at              TIMESTAMPTZ  NOT NULL,
    classified_at             TIMESTAMPTZ,
    CONSTRAINT uq_technical_debt_candidate UNIQUE (run_id, candidate_id),
    CONSTRAINT ck_technical_debt_line       CHECK (line_number >= 1),
    CONSTRAINT ck_technical_debt_confidence CHECK
        (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

CREATE TABLE debt_context (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_debt_id   BIGINT       NOT NULL UNIQUE
                            REFERENCES technical_debt(id) ON DELETE CASCADE,
    context_status      VARCHAR(32)  NOT NULL,
    provider            VARCHAR(64),
    task_key            VARCHAR(128),
    summary             TEXT,
    description         TEXT,
    url                 TEXT,
    acceptance_criteria JSONB        NOT NULL DEFAULT '[]'::jsonb,
    labels              JSONB        NOT NULL DEFAULT '[]'::jsonb,
    enriched_at         TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_debt_context_status CHECK (context_status IN
        ('MATCHED','NOT_FOUND','FAILED','SKIPPED')),
    CONSTRAINT ck_debt_context_matched CHECK
        (context_status <> 'MATCHED' OR (provider IS NOT NULL AND task_key IS NOT NULL)),
    CONSTRAINT ck_debt_context_unmatched CHECK
        (context_status = 'MATCHED' OR (provider IS NULL AND task_key IS NULL))
);

CREATE TABLE external_reference (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_context_id BIGINT       NOT NULL
                        REFERENCES debt_context(id) ON DELETE CASCADE,
    reference_value VARCHAR(255) NOT NULL,
    source          VARCHAR(64)  NOT NULL
);

CREATE TABLE generated_test (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_debt_id BIGINT       NOT NULL UNIQUE
                          REFERENCES technical_debt(id) ON DELETE CASCADE,
    source_code       TEXT,
    framework         VARCHAR(64)  NOT NULL,
    provider          VARCHAR(64)  NOT NULL,
    model             VARCHAR(128) NOT NULL,
    prompt_version    VARCHAR(64)  NOT NULL,
    status            VARCHAR(32)  NOT NULL,
    validation_status VARCHAR(32)  NOT NULL,
    generated_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_generated_test_status CHECK (status IN ('GENERATED','GENERATION_FAILED')),
    CONSTRAINT ck_generated_test_source CHECK
        (source_code IS NOT NULL OR status = 'GENERATION_FAILED'),
    CONSTRAINT ck_generated_test_validation CHECK
        (status <> 'GENERATION_FAILED' OR validation_status = 'NOT_RUN')
);

CREATE TABLE pipeline_error (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            UUID         NOT NULL
                          REFERENCES pipeline_run(id) ON DELETE CASCADE,
    technical_debt_id BIGINT       REFERENCES technical_debt(id) ON DELETE CASCADE,
    stage             VARCHAR(32)  NOT NULL,
    code              VARCHAR(128) NOT NULL,
    message           TEXT         NOT NULL,
    candidate_id      VARCHAR(255),
    recoverable       BOOLEAN      NOT NULL,
    recorded_at       TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_pipeline_run_status      ON pipeline_run (status);
CREATE INDEX idx_pipeline_run_started_at  ON pipeline_run (started_at DESC);
CREATE INDEX idx_pipeline_run_repository  ON pipeline_run (repository_url);

CREATE INDEX idx_technical_debt_run       ON technical_debt (run_id);
CREATE INDEX idx_technical_debt_run_satd  ON technical_debt (run_id, satd);
CREATE INDEX idx_technical_debt_type      ON technical_debt (debt_type);
CREATE INDEX idx_technical_debt_status    ON technical_debt (item_status);

CREATE INDEX idx_debt_context_status      ON debt_context (context_status);
CREATE INDEX idx_external_reference_value ON external_reference (reference_value);
CREATE INDEX idx_external_reference_ctx   ON external_reference (debt_context_id);

CREATE INDEX idx_generated_test_status    ON generated_test (status);
CREATE INDEX idx_generated_test_provider  ON generated_test (provider);

CREATE INDEX idx_pipeline_error_run       ON pipeline_error (run_id);
CREATE INDEX idx_pipeline_error_code      ON pipeline_error (code);
CREATE INDEX idx_pipeline_error_debt      ON pipeline_error (technical_debt_id);
